spring:
  datasource:
    driver-class-name=org:
      mariadb:
        jdbc:
          Driver:
    password:
    url: jdbc:mariadb://localhost:3306/fake_e_bay
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

keycloak:
  realm: SpringBootKeycloak
  auth-server-url: http://localhost:8080/auth
  resource: client-test
  public-client: true
  ssl-required: external
  principal-attribute: preferred_username





