spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/fakeestore/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/fakeestore

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
    url: jdbc:mariadb://localhost:3306/fake_e_bay

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update


server:
  port: 8081

keycloak:
  resource: fakeestore-backend



